### ISSUE TITLE
some suggestion on add_camera_rigs

### ISSUE THREAD

**Issue by Leroy-X** [waylow/Add_Camera_Rigs#2]
I have some idea on this addon, just my idea, list at below:
1. the camera golden guides can setting on the Camera UI properties（N panel）, it will be good for composition;
2. the camera is used parent relation now, but if you move the camera only, and you will press Alt+G reset the position, the camera will be at tail of the bone, but if you use the "Child of" constraint , the Alt+G will move the camera to the head of the bone, it's will be much more better, if I move the camera not in care.
3. Actually , this suggestion is contradiction, you know, when I in camera view, I can move the camera by select camera and press G, but by this addon, if I select camera and press G move the camera in the camera, and it only move the camera, the CTRL bone not flow, and in camera view I can't select the CTRL bone, must select the CTRL in others view.

So I want the CTRL bone move flow the camera (good at in the camera view), and I want the Camera move flow the CTRL bone (good at in others view ), I dont know how to achieve it, because it is contradiction. just idea.

sorry for my bad English,  just my idea thanks :D

![01](https://cloud.githubusercontent.com/assets/13515498/14230110/4bc6c754-f97d-11e5-9dfe-da92d6f958e6.png)
![02](https://cloud.githubusercontent.com/assets/13515498/14230111/4f974548-f97d-11e5-898e-929efd6aedac.png)
![03](https://cloud.githubusercontent.com/assets/13515498/14230112/518397d0-f97d-11e5-8082-99e9489bab63.png)

**Comment by waylow** [comment]
Added the comp guides
and added some blank drivers so the user can only move the camera via the rig
(that solves issue 2 and 3 at the same time)

cheers

**Comment by Leroy-X** [comment]
wa, you are cool, so fast on code, and the 3 that I want say,,,,
![05](https://cloud.githubusercontent.com/assets/13515498/14231023/1dd84c28-f9a5-11e5-928c-3a8e3f6e0e72.png)

anyway, thanks very much, I am think this too contradiction, unless the camera and the CTRL bone is one object , that means we don't need the CTRL bone, just the camera,,,,,,,,,,,,,,,,,,,,,my english too bad,,,sorry

**Comment by waylow** [comment]
HI Leroy, yeah I can't think of a good solution for that one.
If the CTRL and the camera is the one object, you lose the benefit of all the controls being inside the one armature.
I've tried to make the CTRL widget visible from the camera view but because the user can edit the resolution of the camera output, there is no elegant way to have it always inside the view.  (It would need to be in the centre and therefore obscure the view and be confusing)
If there was a way that when you selected the camera, you actually selected the CTRL bone this would have more applications inside blender than just this instance.  (but I don't know if it's possible)

Cheers

**Comment by Leroy-X** [comment]
Yeah,I am agreed with you, that is I want to say, anyway , I don't know how to solution through the drives or the constraint, it's like a loop, I don't understand the programming,  and like you said, selected the CTRL link to Select Camera, or select the Camera link to select the CTRL bone. 

Thanks very much :hamburger:
